name: sample-cluster
region: "us-east-2"
awsAccountID: "575822346426"
instanceTypes:
  - "t3.micro"
maxNodes: 6
dnsManagement: true
dnsManagementServiceAccount:
  name: external-dns
  namespace: threeport-ingress
tags:
  tier: test

