name: sample-cluster-0
#region: "us-west-1"
awsAccountID: "575822346426"
instanceTypes:
  - "t3.micro"
minNodes: 1
maxNodes: 6
dnsManagement: true
dnsManagementServiceAccount:
  name: external-dns
  namespace: threeport-ingress
tags:
  tier: test

